### ISSUE TITLE
NFT Info Witness throws on empty wallet

### ISSUE THREAD

**Issue by jonesmac** [XYOracleNetwork/sdk-xyo-client-js#1030]
see - https://github.com/orgs/xylabs/projects/1/views/1?pane=issue&itemId=36478493

Observed: when a valid wallet is passed, but no nfts are found, the module throws an error:
```
{
    "message": "Trying to witness empty list",
    "name": "CryptoWalletNftWitness",
    "query": "network.xyo.boundwitness",
    "schema": "network.xyo.error.module",
    "sources": [
        "b4f1b0eba83b58b38bec15bf1fe5d0bb2f36b08cf1c941bbbebca928fcb2bec2"
    ]
}
```

Expected: The module should return an empty array.

**Comment by arietrouw** [comment]
Fixed this by removing empty bw check and also removing the code that was passing back the inPayloads from the nft witness
