### ISSUE TITLE
limit is not being used in getBefore and getAfter when calling api

### ISSUE THREAD

**Issue by arietrouw** [XYOracleNetwork/sdk-xyo-client-js#405]
private async get(params: { order: 'desc' | 'asc'; timestamp: number }, limit = 20) {
    assertEx(limit > 0, 'min limit = 1')
    assertEx(limit <= 100, 'max limit = 100')
    return (
      await this.axios.get<XyoBoundWitness[]>(`${this.config.apiDomain}/archive/${this.config.archive}/block`, {
        ...this.axiosRequestConfig,
        params,
      })
    ).data
  }

  public async getBefore(timestamp: number, limit = 20) {
    return await this.get({ order: 'desc', timestamp }, limit)
  }

  public async getAfter(timestamp: number, limit = 20) {
    return await this.get({ order: 'asc', timestamp }, limit)
  }

**Comment by Trealent777** [comment]
https://github.com/XYOracleNetwork/sdk-xyo-client-js/issues/405#issue-1170459416

**Comment by JoelBCarter** [comment]
As of XYO 2.1, we're using the Module system instead of API endpoints so the individual Modules will take care of handling limits.
