### ISSUE TITLE
Problematic Wallets - Arbitrum

### ISSUE THREAD

**Issue by jonesmac** [XYOracleNetwork/sdk-xyo-client-js#961]
Arbitrum
http://localhost:3000/web3/nfts/wallet/0x05BD8eE915a58eA9bD5d1D64a15BC1E462d555Bf?chainId=42161

[block explorer link](https://arbiscan.io/address/0xB6F16010beb0Fa054593823851E68DbAf288dd51#tokentxnsErc721)

Errors:
```
{
    "message": "Cannot read properties of undefined (reading 'split')",
    "name": "ImageThumbnailWitness",
    "query": "network.xyo.boundwitness",
    "schema": "network.xyo.error.module",
    "sources": [
        "f53d14aecb1eab2268dac798bf743ff60dcd0f267e3152d07f2135c89ccbdfb6"
    ]
}
```
and
```
{
    "message": "undefined is not a valid TokenType",
    "name": "CryptoWalletNftWitness",
    "query": "network.xyo.boundwitness",
    "schema": "network.xyo.error.module",
    "sources": [
        "c490b069f3c4dc84ecadd29cbdb9a60480d34ba2412b0a9281aa7ba2a5718d60"
    ]
}
```

**Comment by arietrouw** [comment]
This should be fixed with empty wallet witness fix. Need to verify in UI that it no longer happens with latest SDK (2.75.8+)

**Comment by arietrouw** [comment]
Infura returns undefined for some NFTs.  Updated type toTokenType to return null in that case

Client SDK 2.75.15+
