### ISSUE TITLE
Ability to start node using manifest file from CLI

### ISSUE THREAD

**Issue by arietrouw** [XYOracleNetwork/sdk-xyo-client-js#997]
Using a manifest file, the user should be able to start a custom configured node from the CLI

**Comment by JoelBCarter** [comment]
TODO
- [X] Start Node via Manifest
- [ ] Expose via CLI

**Comment by JoelBCarter** [comment]
☝ I wanted to the first part done and then head on to multi-schema support in the config so that I could unblock some other tasks.  Then the plan is to circle back to enabling manifest injection via CLI

**Comment by Sc2KiiiA** [comment]
u2 are Amazing, just saying ..!!
